@localhost=localhost:4004/odata/v4/main

@id=177025f8-be11-451e-a747-497c9d1c5bdd

@customerId=550e8400-e29b-41d4-a716-446655440000

# Produto sem estoque
@productId1=29491592-c3fb-41dd-a0be-84b4fe13194f

@productId2=17693399-cfc2-4ebd-bd8f-03a3c5938c29

GET http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json
Authorization: Basic jeff:jeff
###

GET http://{{localhost}}/SalesOrderHeaders?$filter=id eq {{id}}&$expand=items
Content-Type: application/json
Authorization: Basic camila:camila

###

POST http://{{localhost}}/SalesOrderHeaders
Content-Type: application/json
Authorization: Basic jeff:jeff

{
    "id": "{{id}}",
    "customer_id": "27981940-4ae4-40c6-804b-d3769c9006f7",
    "totalAmount": 398,
    "items": [
        {
            "id": "c23ccfc1-2d10-4274-8e1c-6aa7d95e0300",
            "header_id": "{{id}}",
            "product_id": "{{productId2}}",
            "quantity": 10,
            "price": 2.99
        },
        {
            "id": "1463f1d6-4c71-4822-9497-86ede7ba9f2b",
            "header_id": "{{id}}",
            "product_id": "{{productId2}}",
            "quantity": 6,
            "price": 1.99
        }
    ]
}

###

DELETE http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json
Authorization: Basic jeff:jeff
{}

###

PUT http://{{localhost}}/SalesOrderHeaders(id={{id}})
Content-Type: application/json
Authorization: Basic camila:camila
{}

###

# Buscar todos os pedidos maiores ou iguais a 2 milhões
GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount ge 20000000
Content-Type: application/json
Authorization: Basic camila:camila

###

# Buscar todos os pedidos menores ou iguais a 2 milhões
GET http://{{localhost}}/SalesOrderHeaders?$filter=totalAmount le 20000000
Content-Type: application/json
Authorization: Basic camila:camila

###

# Selecionar somente customer e id do sales order headers
GET http://{{localhost}}/SalesOrderHeaders?$select=customer_id,id
Content-Type: application/json
Authorization: Basic camila:camila

###

# Selecionnar com expand 
GET http://{{localhost}}/SalesOrderHeaders?$select=id,customer&$expand=customer($select=id,email)
Content-Type: application/json
Authorization: Basic camila:camila

###

# Descobrindo a quantidade de registros
GET http://{{localhost}}/SalesOrderHeaders/$count
Content-Type: application/json
Authorization: Basic camila:camila

###

# Buscar os cinco registros
GET http://{{localhost}}/SalesOrderHeaders?$top=5
Content-Type: application/json
Authorization: Basic camila:camila

###

# Paginação - buscar os próximos três registros
GET http://{{localhost}}/SalesOrderHeaders?$top=3&$skip=5
Content-Type: application/json
Authorization: Basic camila:camila

###

# Buscando dados com o $search
GET http://{{localhost}}/SalesOrderHeaders?$search=403c
Content-Type: application/json
Authorization: Basic camila:camila